// フィルターワード定義（X to Twitter 2）
// content.js より分離。content_scripts で filters.js → content.js の順に読み込む。

// ===== ネガティブ判定ワード（強/弱シグナル＋例外）=====
const EN = w => `\\b${w}\\b`;
const STRONG_JP = [
  "政治", "国際政治", "世界政治", "国政", "政局", "総理", "首相", "選挙", "国会", "衆議院", "参議院",
  "自民党", "立憲民主党", "国民民主党", "共産党", "日本維新", "公明党", "与党", "野党", "政権",
  "内閣", "閣僚", "大臣", "法案", "予算案", "解散", "増税", "減税", "消費税", "防衛費",
  "支持率", "不支持率", "党首", "代表選", "官房長官", "首脳会談", "閣僚会談", "党首会談",
  "岸田", "石破", "安倍", "菅", "河野", "高市", "小泉", "玉木", "馬場", "野田", "泉",
  "知事選", "衆院選", "参院選", "衆院", "参院", "地方選", "投開票", "開票", "投票率",
  "争点", "街頭演説", "政見", "補正予算", "政権交代", "デモ", "抗議", "ストライキ",
  "スキャンダル", "汚職", "贈収賄", "脱税", "偽造", "横領", "背任", "インサイダー",
  "陰謀論", "反ワク", "デマ", "フェイク", "捏造", "隠蔽", "メディア支配",
  "情報操作", "プロパガンダ", "グレートリセット", "世界新秩序", "Qアノン", "マイクロチップ",
  "戦争", "戦闘", "侵攻", "攻撃", "ミサイル", "爆撃", "空爆", "砲撃", "報復", "ドローン",
  "軍事", "兵士", "部隊", "紛争", "停戦", "ウクライナ", "ロシア", "プーチン", "ガザ",
  "パレスチナ", "イスラエル", "ハマス", "ヒズボラ", "イラン", "北朝鮮", "核実験",
  "自衛隊", "戦線", "前線", "戦場", "占領", "侵略", "テロ", "テロリスト",
  "習近平", "金正恩", "ネタニヤフ", "ゼレンスキー", "マクロン", "モディ", "エルドアン",
  "中国共産党", "火災", "火事", "出火", "焼失", "炎上", "爆発", "爆発物",
  "交通事故", "事故死", "死亡事故", "人身事故", "事故", "衝突", "追突", "転落", "崩落", "墜落",
  "死亡", "死者", "亡くなり", "亡くなった", "逝去", "訃報", "死傷者", "負傷", "重体",
  "重症", "重傷", "けが", "怪我", "行方不明", "失踪", "自殺", "自殺未遂", "殺人", "殺害",
  "事件", "犯罪", "強盗", "詐欺", "窃盗", "盗難", "密輸", "麻薬", "人身売買",
  "逮捕", "勾留", "起訴", "判決", "懲役", "冤罪", "暴力", "暴行", "虐待",
  "性犯罪", "性暴力", "強制わいせつ", "痴漢", "誘拐", "監禁", "脅迫", "恐喝",
  "サイバー攻撃", "ハッキング", "フィッシング", "銃", "銃撃", "発砲", "刃物", "刺傷", "刺殺",
  "いがみ合い", "いがみあい", "対立", "争い", "喧嘩", "口論", "誹謗中傷", "中傷", "罵倒",
  "侮辱", "嘲笑", "叩き", "大炎上", "敵対", "反目", "内紛", "派閥争い", "分裂",
  "いじめ", "嫌がらせ", "セクハラ", "パワハラ", "モラハラ",
  "犠牲", "悲報", "悲劇", "哀悼", "追悼", "遺体", "遺族", "心肺停止", "救急搬送",
  "津波", "地震", "震災", "台風", "豪雨", "大雨", "記録的豪雨", "河川氾濫", "高潮",
  "洪水", "土砂災害", "地滑り", "噴火", "火山噴火", "竜巻", "大雪", "熱波", "寒波",
  "停電", "断水", "コロナ", "感染者", "感染拡大", "避難指示", "避難所",
  "倒産", "解雇", "リストラ", "不況", "不景気", "物価高", "円安",
  "食中毒", "熱中症", "猛暑", "鳥インフル", "インフル",
  "反AI", "AI規制", "AI禁止", "AI反対", "AI崩壊", "AI消滅", "AI支配", "AIの暴走", "AI暴走",
  "AI戦争", "AI兵器", "AI犯罪", "AIに仕事を奪われる", "AIで失業", "AI大量失業", "人工知能の暴走",
  "シンギュラリティ", "ロボットに支配", "ディープフェイク", "なりすまし動画", "偽動画", "偽音声",
  "扇動", "煽動", "焚きつけ", "焚き付け", "危機を煽る", "不安を煽る", "恐怖を煽る", "パニックを煽る",
  "過激化", "過激派", "デマ拡散", "情報戦", "洗脳", "洗脳される", "誤情報", "虚偽情報", "偽情報",
  "激怒", "怒り心頭", "怒り狂う", "殺意", "殺意を抱く", "憎悪", "憎しみ", "嫌悪感", "吐き気がする",
  "ブチ切れ", "ブチギレ", "キレた", "切れた", "頭に来る", "頭にきた", "許せない", "許すまじ",
  "復讐", "復讐を誓う", "恨み", "敵意", "軽蔑", "侮蔑", "見下し", "見下す", "マウント", "マウンティング",
  "アフガニスタン", "イラク", "シリア", "イエメン", "スーダン", "リビア", "ソマリア",
  "ミャンマー", "レバノン", "ベネズエラ", "ベラルーシ", "アルメニア", "アゼルバイジャン",
  "カシミール", "エチオピア", "コンゴ", "ハイチ", "台湾", "南シナ海",
  "NAFO", "ナフォ", "フェラ軍",
  "ワシントン", "ジェファーソン", "リンカーン", "ルーズベルト", "ケネディ", "ニクソン",
  "レーガン", "クリントン", "オバマ", "トランプ", "バイデン", "ブッシュ", "ジョンソン",
  "トルーマン", "アイゼンハワー", "アダムズ", "マディソン", "モンロー", "ジャクソン",
  "バンビューレン", "ハリソン", "テイラー", "フィルモア", "ピアース", "ブキャナン",
  "グラント", "ヘイズ", "ガーフィールド", "アーサー", "クリーブランド", "マッキンリー",
  "タフト", "ウィルソン", "ハーディング", "クーリッジ", "フーヴァー", "フォード", "カーター",
  "スターリン", "レーニン", "毛沢東", "ヒトラー", "チャーチル", "サッチャー", "ゴルバチョフ",
  "エリツィン", "ムバラク", "カダフィ", "サダム", "ビンラディン", "チャベス", "カストロ",
  "マドゥロ", "ルーラ", "ボルソナロ", "トルドー", "スターマー", "スナク", "ショルツ",
  "メルケル", "メローニ", "ムッソリーニ", "フランコ", "サンチェス", "サルコジ", "シラク",
  "ドゴール", "ルカシェンコ", "アサド", "金日成", "金正日", "蒋介石", "マンデラ", "ガンジー",
  "ナポレオン", "カエサル",
  "為替", "為替介入", "為替相場", "円相場", "円高", "日米", "日露", "日韓",
  "米国", "米軍", "米政府", "米大統領", "米中",
  "露軍", "露政府", "露大統領", "仏軍", "仏政府", "仏大統領",
  "英軍", "英政府", "英首相", "独軍", "独政府", "独首相",
  "中国政府", "中国軍"
];
const STRONG_EN = [
  "politics", "political", "politician", "election", "president", "presidential",
  "campaign", "vote", "voting", "congress", "senate", "senator", "parliament",
  "parliamentarian", "prime minister", "premier", "chancellor", "cabinet", "minister",
  "lawmaker", "lawmakers", "legislation", "government", "democrat", "republican",
  "maga", "trump", "biden", "impeachment", "scandal", "corruption", "corrupt",
  "bribery", "bribe", "coup", "regime", "authoritarian", "dictatorship", "dictator",
  "sanction", "sanctions", "tariff", "tariffs", "trade war", "nato", "summit", "treaty",
  "diplomacy", "diplomatic", "geopolitical", "border", "immigrant", "immigration",
  "deportation", "shooting", "shooter", "gunman", "killed", "killing", "kills",
  "death", "deaths", "dead", "died", "dying", "murder", "massacre", "terrorist",
  "terrorism", "attack", "attacks", "bombing", "bomb", "explosion", "explosive",
  "wildfire",
  "crash", "accident", "accidents", "injured", "injury",
  "victim", "victims", "suicide", "protest", "riots", "riot", "war", "wars",
  "military", "soldier", "soldiers", "troops", "invasion", "occupation", "annexation",
  "missile", "missiles", "nuclear", "ceasefire", "ukraine", "russia", "putin",
  "gaza", "palestine", "israel", "hamas", "iran", "isis", "taliban", "xi jinping",
  "kim jong un", "netanyahu", "zelensky", "macron", "modi", "erdogan",
  "deep state", "new world order", "conspiracy", "conspiracy theory", "false flag",
  "rigged", "stolen election", "fake news", "propaganda", "censorship",
  "airstrike", "air strike", "artillery", "bombardment", "insurgent", "militant",
  "extremism", "radicalization", "inflation", "recession", "layoff", "layoffs",
  "bankruptcy", "unemployment", "earthquake", "flood", "floods", "hurricane",
  "tornado", "storm", "blizzard", "heat wave", "cold snap", "volcano", "volcanic",
  "tsunami", "landslide", "mudslide", "typhoon", "cyclone", "drought", "famine",
  "hostage", "kidnap", "kidnapping", "rape", "abuse", "arson",
  "theft", "robbery", "burglary", "fraud", "scam", "scammer", "embezzlement",
  "trafficking", "smuggling", "drugs", "narcotics", "ransomware", "phishing",
  "hacking", "cyberattack", "cyber attack", "casualties", "casualty", "fatality", "fatalities",
  "argument", "arguments", "arguing", "quarrel", "feud", "feuding", "hostility",
  "hostile", "toxic", "trolling", "trolls", "harassment", "cyberbullying", "bullying",
  "insult", "insults", "mocking", "ridicule", "hatred", "hate speech", "bigotry",
  "racism", "xenophobia", "misogyny", "homophobia", "discrimination",
  "artificial intelligence", "AI takeover", "AI apocalypse", "AI doom", "robot uprising",
  "singularity", "killer robots", "autonomous weapons", "AI weapons", "deepfake", "deepfakes",
  "AI replacing jobs", "AI job losses", "AI layoffs", "AI ban", "ban AI", "AI regulation",
  "incite", "incites", "inciting", "incitement", "fearmongering", "scaremongering", "hysteria",
  "misinformation", "disinformation", "brainwashing", "smear campaign", "hate campaign", "mob mentality",
  "rage", "furious", "fury", "enraged", "livid", "seething", "murderous", "despise", "despised",
  "contempt", "loathing", "loathe", "disgusting", "revolting", "repulsive", "vile", "revenge",
  "vendetta", "grudge", "animosity", "condescending", "patronizing", "smug",
  "international politics", "world politics", "political situation", "political instability",
  "national diet", "house of representatives", "house of councillors", "ldp",
  "liberal democratic party", "constitutional democratic party", "japanese communist party",
  "communist party", "komeito", "nippon ishin", "ruling party", "opposition party",
  "opposition parties", "administration", "bill", "bills", "budget bill", "budget proposal",
  "dissolution", "dissolve parliament", "tax increase", "tax hike", "tax hikes", "tax cut",
  "tax cuts", "consumption tax", "defense budget", "approval rating", "approval ratings",
  "disapproval rating", "party leader", "leadership election", "leadership race",
  "chief cabinet secretary", "kishida", "ishiba", "abe", "suga", "kono", "takaichi",
  "koizumi", "tamaki", "baba", "noda", "izumi", "gubernatorial election",
  "lower house election", "upper house election", "local election", "local elections",
  "vote counting", "voter turnout", "campaign rally", "campaign rallies",
  "supplementary budget", "change of government", "power transfer", "labor strike",
  "tax evasion", "tax fraud", "forgery", "counterfeit",
  "breach of trust", "insider trading", "great reset", "qanon", "q anon", "microchip",
  "microchips",     "antivax", "anti-vax",
  "fabrication", "fabricated", "cover-up", "coverup", "media control", "media manipulation",
  "information manipulation", "battle", "combat", "shelling", "retaliation", "drone",
  "drones", "drone strike", "hezbollah", "north korea",
  "north korean", "nuclear test", "nuclear testing", "self defense forces", "jsdf",
  "front line", "frontline", "battlefield", "chinese communist party", "ccp",
  "traffic accident", "car accident", "vehicle accident", "accidental death",
  "fatal accident", "deadly accident", "collision", "collide", "plunge", "plunged",
  "fell off", "collapse", "collapsed", "passed away", "obituary", "obituaries",
  "critical condition", "critically injured", "serious injury", "seriously injured",
  "missing", "missing person", "disappeared", "suicide attempt", "attempted suicide",
  "incident", "incidents", "crime", "crimes", "criminal", "arrest", "arrested",
  "arrests", "detained", "indictment", "indicted", "verdict", "imprisonment",
  "prison sentence", "wrongful conviction", "violence", "violent", "assault",
  "assaulted", "sex crime", "sexual violence", "sexual assault", "groping", "groped",
  "held captive", "threat", "threats", "threatening", "intimidation", "blackmail",
  "extortion", "gun", "guns", "firearm", "firearms", "gunfire", "shots fired",
  "opened fire", "knife", "knife attack", "stabbing", "stabbed", "heavy rain",
  "torrential rain", "downpour", "record rainfall", "river overflow", "storm surge",
  "eruption", "erupted", "heavy snow", "snowstorm", "power outage", "blackout",
  "water outage", "covid", "covid-19", "coronavirus", "infection", "infections",
  "outbreak", "evacuation order",     "evacuation", "evacuated", "downsizing",
  "economic downturn", "downturn", "rising prices", "soaring prices", "price hikes",
  "weak yen", "food poisoning", "heatstroke", "heat stroke", "extreme heat",
  "scorching heat", "bird flu", "avian flu", "influenza", "quarreling",
  "bickering", "confrontation", "standoff", "strife",
  "brawl", "slander", "defamation", "defamatory", "bashing", "slam", "slamming",
  "cancel culture", "antagonism", "infighting", "internal strife", "factional",
  "factionalism", "split", "division", "divided", "schism", "sexual harassment",
  "power harassment", "moral harassment", "sacrifice", "sad news", "tragedy", "tragic",
  "mourning", "grief", "memorial", "dead body", "remains", "bereaved", "cardiac arrest",
  "hospitalized", "rushed to hospital", "against ai", "AI collapse", "AI meltdown",
  "AI extinction", "AI domination", "AI war", "AI crime", "AI unemployment",
  "runaway AI", "impersonation video", "fake video", "fake audio", "provoke",
  "provoking", "stir up", "inciting panic", "spreading fake news", "spreading lies",
  "share disinformation", "information warfare", "false information", "nauseating",
  "sickening", "infuriating", "infuriated", "pissed off", "unforgivable",
  "cannot forgive", "can't forgive", "cant forgive", "won't forgive", "one-up", "one-upping", "look down on",
  "looking down", "snapped", "lost it",
  "afghanistan", "iraq", "syria", "yemen", "sudan", "libya", "somalia", "myanmar",
  "lebanon", "venezuela", "belarus", "armenia", "azerbaijan", "kashmir",
  "ethiopia", "congo", "haiti", "taiwan", "south china sea",
  "nafo", "north atlantic fellas", "fella army",
  "washington", "jefferson", "lincoln", "roosevelt", "kennedy", "nixon", "reagan",
  "clinton", "obama", "bush", "stalin", "lenin", "mao zedong", "mao", "hitler",
  "churchill", "thatcher", "gorbachev", "yeltsin", "mubarak", "gaddafi", "saddam",
  "saddam hussein", "bin laden", "osama bin laden", "chavez", "castro", "maduro",
  "lula", "bolsonaro", "trudeau", "boris johnson", "starmer", "sunak", "scholz",
  "merkel", "meloni", "mussolini", "franco", "sanchez", "sarkozy", "chirac",
  "de gaulle", "lukashenko", "assad", "kim il sung", "kim jong il", "chiang kai shek",
  "mandela", "gandhi", "napoleon", "caesar",
  "exchange rate", "foreign exchange", "fx", "us-china", "us-japan", "japan-us",
  "us military", "us government", "us president"
];
const WEAK_JP = ["論争", "議論", "意見対立", "クレーム", "苦情", "トラブル", "もめ事", "もめごと", "険悪", "ギスギス", "騒動", "不安", "心配", "ストレス", "パニック", "恐慌", "買い占め", "賛否", "賛否両論", "物議", "物議を醸す", "波紋を呼ぶ", "批判殺到", "非難殺到", "反発", "バックラッシュ", "火種", "いざこざ", "ムカつく", "イライラ", "うんざり", "最悪", "呆れた", "嫌い", "怒り", "絶望", "気持ち悪い", "嫌悪", "ゲンナリ", "ドン引き", "モヤモヤ", "ざわつく", "ワクチン", "露", "仏", "韓国"];
const WEAK_EN = ["controversy", "controversial", "dispute", "disputes", "debate", "debates", "complaint", "complaints", "trouble", "friction", "tension", "tensions", "stressed", "stress", "worried", "worry", "panic", "outrage", "uproar", "outcry", "furor", "backlash", "alarm", "annoyed", "annoying", "frustrated", "frustrating", "angry", "mad", "fed up", "sick of", "tired of", "gross", "disgusted", "worst", "despair", "hopeless", "disagreement", "disagreements", "strained", "tense relations", "anxiety", "anxious", "panic buying", "hoarding", "for and against", "mixed reactions", "mixed opinions", "stirring controversy", "causing a stir", "caused a stir", "flood of criticism", "criticized heavily", "squabble", "squabbles", "appalled", "appalling", "dislike", "hate", "anger", "cringe", "cringed", "put off", "uneasy", "unease", "unsettled", "adams", "madison", "monroe", "jackson", "van buren", "harrison", "taylor", "fillmore", "pierce", "buchanan", "grant", "hayes", "garfield", "arthur", "cleveland", "mckinley", "taft", "wilson", "harding", "coolidge", "hoover", "ford", "carter", "truman", "eisenhower", "johnson", "conflict", "conflicts", "fight", "fights", "fighting", "strike", "strikes", "fire", "fires", "shelter", "fake", "flu", "vaccine", "vaccines", "vaccination", "yen", "south korea"];
const JAPAN_SUBJECT_G = new RegExp("(?:日本では|日本人は|日本人が|日本は|日本人|この国は|この国では|japanese people|japanese are|japanese society|japanese government|in japan|japan is|this country)", "gi");

const NEGATIVE_EXCEPT = /(?:火災保険|火災報知器|事故物件|防災|募金|チャリティ|寄付|復興支援|被災地支援|バリアフリー|無事|無傷|全員無事|けがなし|軽傷のみ|助かった)/i;
const NEGATIVE_STRONG = new RegExp(`(?:${STRONG_JP.join("|")})|(?:${STRONG_EN.map(EN).join("|")})`, "i");
const NEGATIVE_WEAK_G = new RegExp(`(?:${WEAK_JP.join("|")})|(?:${WEAK_EN.map(EN).join("|")})`, "gi");
